### ISSUE TITLE
Missing settings

### ISSUE THREAD

**Issue by juanmiret** [pekpon/sails-shop#1]
Hi! I'm trying to test your app but there's some settings file missing (sails.config.settings is undefined)

Any help?

**Comment by mylastore** [comment]
same here but just comment line 2 under services/mail.js  this line //var server = email.server.connect(sails.config.settings.email); and the app runs.

**Comment by javiquero** [comment]
juanmiret, 

You can create a 'settings.js' file in the folder config that contains this:
module.exports.settings = {
          email: 'myemailaddress@nobody.com'
}

**Comment by mylastore** [comment]
that worked for me
